name: uuid-tool
base: core20
version: 'v0.0.1'
summary: CLI tool for generating v4 UUID values.
description: |
  uuid-tool is a tool for generating v4 UUID values.

grade: stable
confinement: strict
architectures:
  - build-on: [amd64, arm64, armhf]

apps:
  uuid-tool:
    command: bin/uuid-tool

parts:
  uuid-tool:
    plugin: go
    go-channel: 1.16/stable
    source: https://github.com/shoenig/uuid-tool
    source-type: git
    source-tag: v0.0.1
    build-packages:
      - git
